In [23]:
from keras.preprocessing.sequence import TimeseriesGenerator
import pandas as pd

In [17]:
train_t = [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
           [200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
           [300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310],
           [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
           [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510],
           [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
           [700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710],
           [800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810],
           [900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910],
           [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
           [1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110],
           [1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210],
           [1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310],
           [1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410],
          ]

y_t = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
         

# How many record to take into account
length = 2

batch_size = 1

# 1 beacause it's univariate
n_features = 1

generator = TimeseriesGenerator(train_t, None, length=length, batch_size=5)

TypeError: object of type 'NoneType' has no len()

a     b     c     d     e     f     g     h     i     j     k
0    100   101   102   103   104   105   106   107   108   109   110
1    200   201   202   203   204   205   206   207   208   209   210
2    300   301   302   303   304   305   306   307   308   309   310
3    400   401   402   403   404   405   406   407   408   409   410
4    500   501   502   503   504   505   506   507   508   509   510
5    600   601   602   603   604   605   606   607   608   609   610
6    700   701   702   703   704   705   706   707   708   709   710
7    800   801   802   803   804   805   806   807   808   809   810
8    900   901   902   903   904   905   906   907   908   909   910
9   1000  1001  1002  1003  1004  1005  1006  1007  1008  1009  1010
10  1100  1101  1102  1103  1104  1105  1106  1107  1108  1109  1110
11  1200  1201  1202  1203  1204  1205  1206  1207  1208  1209  1210
12  1300  1301  1302  1303  1304  1305  1306  1307  1308  1309  1310
13  1400  1401  1402  1403  1404  1405  1406  1407  1408  1409  1410

In [27]:
from tensorflow.keras.preprocessing import timeseries_dataset_from_array

In [25]:
for i in timeseries_dataset_from_array(pd.DataFrame(train_t, columns=['a', 'b', 'c','d', 'e', 'f', 'g', 'h', 'i', 'j', 'k']), None, 7):
    print(i)

tf.Tensor(
[[[ 100  101  102  103  104  105  106  107  108  109  110]
  [ 200  201  202  203  204  205  206  207  208  209  210]
  [ 300  301  302  303  304  305  306  307  308  309  310]
  [ 400  401  402  403  404  405  406  407  408  409  410]
  [ 500  501  502  503  504  505  506  507  508  509  510]
  [ 600  601  602  603  604  605  606  607  608  609  610]
  [ 700  701  702  703  704  705  706  707  708  709  710]]

 [[ 200  201  202  203  204  205  206  207  208  209  210]
  [ 300  301  302  303  304  305  306  307  308  309  310]
  [ 400  401  402  403  404  405  406  407  408  409  410]
  [ 500  501  502  503  504  505  506  507  508  509  510]
  [ 600  601  602  603  604  605  606  607  608  609  610]
  [ 700  701  702  703  704  705  706  707  708  709  710]
  [ 800  801  802  803  804  805  806  807  808  809  810]]

 [[ 300  301  302  303  304  305  306  307  308  309  310]
  [ 400  401  402  403  404  405  406  407  408  409  410]
  [ 500  501  502  503  504  505  506  50

In [14]:
generator[0]

(array([[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
         [200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210]],
 
        [[200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
         [300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310]],
 
        [[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310],
         [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410]],
 
        [[400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
         [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510]],
 
        [[500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510],
         [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610]]]),
 array([[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310],
        [400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
        [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510],
        [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610],
        [700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710]])

In [15]:
generator[1]

(array([[[ 600,  601,  602,  603,  604,  605,  606,  607,  608,  609,
           610],
         [ 700,  701,  702,  703,  704,  705,  706,  707,  708,  709,
           710]],
 
        [[ 700,  701,  702,  703,  704,  705,  706,  707,  708,  709,
           710],
         [ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
           810]],
 
        [[ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,
           810],
         [ 900,  901,  902,  903,  904,  905,  906,  907,  908,  909,
           910]],
 
        [[ 900,  901,  902,  903,  904,  905,  906,  907,  908,  909,
           910],
         [1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
          1010]],
 
        [[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009,
          1010],
         [1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109,
          1110]]]),
 array([[ 800,  801,  802,  803,  804,  805,  806,  807,  808,  809,  810],
        [ 900,  901,  902,  903,  904, 

In [16]:
generator[2]

(array([[[1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109,
          1110],
         [1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209,
          1210]],
 
        [[1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209,
          1210],
         [1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309,
          1310]]]),
 array([[1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310],
        [1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410]]))

In [59]:
generator[3]

(array([], dtype=float64), array([], dtype=float64))